### ISSUE TITLE
fossOutput exception does not have attribute 'output'

### ISSUE THREAD

**Issue by Kazzira** [socs-dev-env/DoSOCS#20]
When I run the command:

/DoSOCS-master/src$ python DoSPDX.py --scan  -p /vbox/Packages/nu-master.zip --scanOption fossology --print tag

I get back:

Traceback (most recent call last):
  File "DoSPDX.py", line 145, in <module>
    main(sys.argv[1:])
  File "DoSPDX.py", line 134, in main
    spdxDoc.generateSPDXDoc(scanOption)
  File "/media/sf_vbox/DoSOCS-master (1)/DoSOCS-master/src/spdx.py", line 364, in generateSPDXDoc
    tempFileInfo.populateFileInfo(self.scanOption)
  File "/media/sf_vbox/DoSOCS-master (1)/DoSOCS-master/src/fileInfo.py", line 479, in populateFileInfo
    fossOutput = str(e.output)
AttributeError: 'exceptions.OSError' object has no attribute 'output'

**Comment by socsdev** [comment]
It may be because of wrong fossology nomos path or you didn't have permissions to your fossology.

**Comment by ttgurney** [comment]
I was able to recreate this with:

    $ ./DoSPDX.py --scan -p empty.tar.bz2 --scanOption fossology --print tag
    Traceback (most recent call last):
      File "./DoSPDX.py", line 145, in <module>
        main(sys.argv[1:])
      File "./DoSPDX.py", line 134, in main
        spdxDoc.generateSPDXDoc(scanOption)
      File "/home/tgurney/DoSOCS-testing/DoSOCS/spdx.py", line 330, in generateSPDXDoc
        tempFileInfo.populateFileInfo(scanOption)
      File "/home/tgurney/DoSOCS-testing/DoSOCS/fileInfo.py", line 458, in populateFileInfo
        fossOutput = str(e.output)
    AttributeError: 'exceptions.OSError' object has no attribute 'output'

It's worth noting that there's no mention of an "output" attribute on OSError instances here: https://docs.python.org/2/library/exceptions.html#exceptions.OSError

**Comment by ttgurney** [comment]
Also, to correct the root cause, look in settings.py; try changing FOSSOLOGY_PATH to `/usr/share/fossology/nomos/agent/nomos` (this is the location of the nomos binary in the latest version of FOSSology)

**Comment by zwmcfarland** [comment]
This is a very "interesting" piece of FOSSology that you have stumbled upon here. Basically the call to nomos executes successfully, but returns a non zero exit code. Since it returns a non zero exit code it throws an exception in python. So then we have to catch that "failed" call and get its output because the call was actually successful. This leads to the problem you are seeing here, if there is an actual problem with the nomos call then you get a "secondary" error that loses its original message definition and throws this non-helpful message. 

So, we could update the settings.py with the latest default install location of FOSSology, but this is already a explicit instruction stated by the install script, furthermore it won't really help those that have installed FOSSology to a different directory (namely me :D).

I think the proper thing to do would probably be to try and determine if nomos should really be returning a non zero exit code, and if not submit an issue to the FOSSology project (which is also an open source project, if you where unaware).

**Comment by zwmcfarland** [comment]
For the time being I have added some more specific error handling around the FOSSology call, so it should give you a more useful message if something isn't configured correctly.

Commit https://github.com/socs-dev-env/DoSOCS/commit/9e31ddb1ff71de9554c7ba18738651949c2f5fce
